/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dangnhap;
import Repository.nhanVienRepositori;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.khachHang;
import Repository.khachHangRepositori;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Admin
 */
public class viewKhachHang extends javax.swing.JPanel {
  private DefaultTableModel dtbKh;
    private khachHangRepositori khRepo = new khachHangRepositori();
    ArrayList<khachHang> khh = new ArrayList<>();
    khachHang khach = new khachHang();
    /**
     * Creates new form viewKhachHang
     */
    public viewKhachHang() {
        initComponents();
        loadData();
    }
       public void loadData() {
        dtbKh = (DefaultTableModel) tblKhachHang.getModel();
        dtbKh.setRowCount(0);
        khh = khRepo.getAll(); // Cập nhật danh sách nhân viên từ cơ sở dữ liệu
        for (khachHang a : khh) {
            Object[] n = new Object[5];
            n[0] = a.getIdKhachHang();
            n[1] = a.getTenKhachHang();
            n[2] = a.getSdt();
            n[3] = a.getDiaChi();
            n[4] = a.isTrangThai(); 
            dtbKh.addRow(n);
        }
        updateMaKhachHangField();
    }

    private void detailKhachHang(int index) {
        khachHang nv = khRepo.getAll().get(index);
        txtIDKH.setText(String.valueOf(nv.getIdKhachHang()));
        txtTenKH.setText(nv.getTenKhachHang());
        txtSdt.setText(nv.getSdt());
        txtDiaChi.setText(nv.getDiaChi());
        boolean trangThai = nv.isTrangThai();
        if (trangThai == true) {
            rdoAc.setSelected(true);
        } else {
            rdoIN.setSelected(true);
        }
    }

//    public nhanVien getFormData() {
//        nhanVien nv = new nhanVien();
//        String ten, diaChi, email, sdt, taiKhoan, matKhau, ngayTao, ngaySua;
//        ten = txtName.getText();
//        diaChi = txtDiaChi.getText();
//        email = txtEmail.getText();
//        sdt = txtSDT.getText();
//        taiKhoan = txtTenDangNhap.getText();
//        matKhau = txtMatKhau.getText();
//        boolean chucVu = rdoNhanVien.isSelected();
//        boolean trangThai = rdoDangLam.isSelected();
//        return nv;
//    }
    public khachHang getFormData() {
        try {
            khachHang kh = new khachHang();
            kh.setIdKhachHang(Integer.parseInt(txtIDKH.getText()));
            kh.setTenKhachHang(txtTenKH.getText());
            kh.setDiaChi(txtDiaChi.getText());
            kh.setSdt(txtSdt.getText());
            String trangThai = "";
            if (rdoAc.isSelected()) {
                trangThai = "Activer";
            } else if (rdoIN.isSelected()) {
                trangThai = "Inativer";
            }
            // Đặt giá trị trạng thái dưới dạng boolean
//        boolean trangThai = false;
//        if (txtTrangThai.getText().equalsIgnoreCase("1")) {
//            trangThai = true;
//        }
//        nv.setTrangthai(trangThai);
            return kh;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public boolean checkDuLieu() {
        if (txtTenKH.getText().trim().length() > 255) {
            JOptionPane.showMessageDialog(null, "Tên Nhân Viên không được vượt quá 255 ký tự.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean isValidPhoneNumber(String phoneNumber) {
        // Check if the phone number has 10 or 11 digits, starts with 0, and contains only digits
        return (phoneNumber.length() == 10 || phoneNumber.length() == 11) && phoneNumber.startsWith("0") && phoneNumber.matches("\\d+");
    }

    private void updateMaKhachHangField() {
        if (khh.size() > 0) {
            int maxMaNV = khh.get(khh.size() - 1).getIdKhachHang();
            txtIDKH.setText(String.valueOf(maxMaNV + 1));
        } else {
            txtIDKH.setText("1");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdoIN = new javax.swing.JRadioButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTimKh = new javax.swing.JTextField();
        txtIDKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        rdoAc = new javax.swing.JRadioButton();
        btnXoa = new javax.swing.JButton();

        buttonGroup1.add(rdoIN);
        rdoIN.setText("Inativer");

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnReset.setText("Làm Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Số Điện Thoại ", "Trạng Thái"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        jLabel7.setText("Tìm Kiếm");

        txtTimKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKhActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("Quản Lý Khách Hàng");

        jLabel2.setText("Mã Khách Hàng");

        jLabel3.setText("Địa Chỉ");

        jLabel6.setText("Trạng Thái");

        jLabel4.setText("Tên Khách Hàng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setText("Số Điện Thoại");

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gear.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoAc);
        rdoAc.setText("Activer");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThem))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnSua)
                                .addGap(113, 113, 113)
                                .addComponent(btnXoa)
                                .addGap(117, 117, 117)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTimKh, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txtIDKH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(txtSdt))
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdoAc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdoIN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(rdoIN)
                    .addComponent(txtIDKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(rdoAc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTimKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTenKH.setText("");
        txtIDKH.setText("");
        txtDiaChi.setText("");
        txtSdt.setText("");
        buttonGroup1.clearSelection();
        JOptionPane.showMessageDialog(this, "Reset thành công");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        int index = tblKhachHang.getSelectedRow();
        this.detailKhachHang(index);
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtTimKhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKhActionPerformed
        // TODO add your handling code here:
        TableRowSorter<DefaultTableModel> ab = new TableRowSorter<>(dtbKh);
        tblKhachHang.setRowSorter(ab);
        ab.setRowFilter(RowFilter.regexFilter(txtTimKh.getText()));
    }//GEN-LAST:event_txtTimKhActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (txtTenKH.getText().isEmpty() || txtSdt.getText().isEmpty() || txtDiaChi.getText().isEmpty() || txtSdt.getText() == null) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu");
                return;
            }
            if (!checkDuLieu()) {
                return;
            }
            if (!isValidPhoneNumber(txtSdt.getText())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ! "
                    + "\n Vui lòng nhập số điện thoại có độ dài 10 hoặc 11 chữ số "
                    + "\n Số điện thoại phải bắt đầu bằng 0.");
                return; // Exit the method if the phone number is invalid
            }

            khachHang kh = getFormData();
            if (khRepo.add(kh)) {
                loadData();
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                updateMaKhachHangField();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (txtTenKH.getText().isEmpty() || txtSdt.getText().isEmpty() || txtDiaChi.getText().isEmpty() || txtSdt.getText() == null) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu");
                return;
            }
            if (!checkDuLieu()) {
                return;
            }
            if (!isValidPhoneNumber(txtSdt.getText())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ! "
                    + "\n Vui lòng nhập số điện thoại có độ dài 10 hoặc 11 chữ số "
                    + "\n Số điện thoại phải bắt đầu bằng 0.");
                return; // Exit the method if the phone number is invalid
            }

            if (tblKhachHang.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Chọn nhân viên cần sửa");
                return;
            }
            khachHang kh = getFormData();
            khRepo.Edit(kh);
            loadData();
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
            updateMaKhachHangField();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        try {
            int row = tblKhachHang.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn nhân viên cần xóa");
                return;
            }
            int manv = khh.get(row).getIdKhachHang();
            khachHang nv = new khachHang();
            nv.setIdKhachHang(manv);
            if (khRepo.Delete(nv) > 0) {
                loadData();
                JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công");

            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoAc;
    private javax.swing.JRadioButton rdoIN;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtIDKH;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKh;
    // End of variables declaration//GEN-END:variables
}
