/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dangnhap;
import Model.vouCher1;
import Repository.vouCherRepositori;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Admin
 */
public class viewVocher extends javax.swing.JPanel {
 private DefaultTableModel dtm;
    private vouCherRepositori nvRepo = new vouCherRepositori();
    ArrayList<vouCher1> v = new ArrayList<>();
    vouCher1 n = new vouCher1();
    /**
     * Creates new form viewVocher
     */
    public viewVocher() {
        initComponents();
         loadData();
    }
 public void loadData() {
        dtm = (DefaultTableModel) tblVoucher.getModel();
        dtm.setRowCount(0);
        v = nvRepo.getAll(); // Cập nhật danh sách nhân viên từ cơ sở dữ liệu
        for (vouCher1 a : v) {
            Object[] n = new Object[6];
            n[0] = a.getIdVoucher();
            n[1] = a.getTen();
            n[2] = a.getPhanTramGiam();
            n[3] = a.getNgayBatDau();
            n[4] = a.getNgayKetThuc();
            n[5] = a.isTrangThai();
            dtm.addRow(n);
        }
        updateMaNhanVienField();
    }
      private void detailVoucher(int index) {
        vouCher1 nv = nvRepo.getAll().get(index);
        txtIDVoucher.setText(String.valueOf(nv.getIdVoucher()));
        txtNameVoucher.setText(nv.getTen());
        txtPhamTramGiam.setText(String.valueOf(nv.getPhanTramGiam()));
        txtNgayVoucherBD.setText(nv.getNgayBatDau());
        txtNgayVoucherKT.setText(nv.getNgayKetThuc());
        boolean trangThai = nv.isTrangThai();
        if (trangThai == true) {
            rdoConHan.setSelected(true);
        } else {
            rdoHetHan.setSelected(true);
        }
    }

//    public nhanVien getFormData() {
//        nhanVien nv = new nhanVien();
//        String ten, diaChi, email, sdt, taiKhoan, matKhau, ngayTao, ngaySua;
//        ten = txtName.getText();
//        diaChi = txtDiaChi.getText();
//        email = txtEmail.getText();
//        sdt = txtSDT.getText();
//        taiKhoan = txtTenDangNhap.getText();
//        matKhau = txtMatKhau.getText();
//        boolean chucVu = rdoNhanVien.isSelected();
//        boolean trangThai = rdoDangLam.isSelected();
//        return nv;
//    }
    public vouCher1 getFormData() {
        try {
            vouCher1 nv = new vouCher1();
            nv.setIdVoucher(Integer.parseInt(txtIDVoucher.getText()));
            nv.setTen(txtNameVoucher.getText());
             nv.setPhanTramGiam(Integer.parseInt(txtPhamTramGiam.getText()));
             nv.setNgayBatDau(txtNgayVoucherBD.getText());
             nv.setNgayKetThuc(txtNgayVoucherKT.getText());
            String trangThai = "";
            if (rdoConHan.isSelected()) {
                trangThai = "Còn Hạn";
            } else if (rdoHetHan.isSelected()) {
                trangThai = "Hết Hạn";
            }
            // Đặt giá trị trạng thái dưới dạng boolean
//        boolean trangThai = false;
//        if (txtTrangThai.getText().equalsIgnoreCase("1")) {
//            trangThai = true;
//        }
//        nv.setTrangthai(trangThai);
            return nv;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public boolean checkDuLieu() {
        if (txtNameVoucher.getText().trim().length() > 255) {
            JOptionPane.showMessageDialog(null, "Tên Nhân Viên không được vượt quá 255 ký tự.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean isValidPhoneNumber(String phoneNumber) {
        // Check if the phone number has 10 or 11 digits, starts with 0, and contains only digits
        return (phoneNumber.length() == 10 || phoneNumber.length() == 11) && phoneNumber.startsWith("0") && phoneNumber.matches("\\d+");
    }

    private void updateMaNhanVienField() {
        if (v.size() > 0) {
            int maxMaNV = v.get(v.size() - 1).getIdVoucher();
            txtIDVoucher.setText(String.valueOf(maxMaNV + 1));
        } else {
            txtIDVoucher.setText("1");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        rdoConHan = new javax.swing.JRadioButton();
        btnXoa = new javax.swing.JButton();
        rdoHetHan = new javax.swing.JRadioButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiemVocher = new javax.swing.JTextField();
        txtNgayVoucherBD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayVoucherKT = new javax.swing.JTextField();
        txtPhamTramGiam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDVoucher = new javax.swing.JTextField();
        txtNameVoucher = new javax.swing.JTextField();

        buttonGroup1.add(rdoConHan);
        rdoConHan.setText("Còn Hạn");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoHetHan);
        rdoHetHan.setText("Hết Hạn");

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày Bắt Đầu");

        jLabel7.setText("Tìm Kiếm");

        jLabel5.setText("Ngày Kết Thúc");

        txtTimKiemVocher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemVocherActionPerformed(evt);
            }
        });

        jLabel8.setText("Phần Trăm Giảm");

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã VouCher", "Tên VouCher", "Phần Trăm Giảm", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucher);

        jLabel6.setText("Trạng Thái");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gear.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Voucher");

        jLabel2.setText("Mã Voucher");

        jLabel3.setText("Tên Voucher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNameVoucher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtIDVoucher, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoConHan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNgayVoucherBD, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtPhamTramGiam))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNgayVoucherKT, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTimKiemVocher))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnXoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLamMoi)
                                        .addGap(150, 150, 150))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnThem)
                        .addGap(106, 106, 106)
                        .addComponent(btnSua))
                    .addComponent(jScrollPane1))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayVoucherBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayVoucherKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPhamTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTimKiemVocher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNameVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoConHan)
                    .addComponent(rdoHetHan)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblVoucher.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn nhân viên cần xóa");
                return;
            }
            int manv = v.get(row).getIdVoucher();
            vouCher1 nv = new vouCher1();
            nv.setIdVoucher(manv);
            if (nvRepo.Delete(nv) > 0) {
                loadData();
                JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công");

            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtNameVoucher.setText("");
        txtIDVoucher.setText("");
        txtPhamTramGiam.setText("");
        txtNgayVoucherBD.setText("");
        txtNgayVoucherKT.setText("");
        buttonGroup1.clearSelection();
        JOptionPane.showMessageDialog(this, "Reset thành công");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtTimKiemVocherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemVocherActionPerformed
        // TODO add your handling code here:
        TableRowSorter<DefaultTableModel> ab = new TableRowSorter<>(dtm);
        tblVoucher.setRowSorter(ab);
        ab.setRowFilter(RowFilter.regexFilter(txtTimKiemVocher.getText()));
    }//GEN-LAST:event_txtTimKiemVocherActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        // TODO add your handling code here:
        int index = tblVoucher.getSelectedRow();
        this.detailVoucher(index);
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNameVoucher.getText().isEmpty() || txtNgayVoucherBD.getText().isEmpty() || txtNgayVoucherKT.getText().isEmpty() || txtPhamTramGiam.getText() == null) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu");
                return;
            }
            if (!checkDuLieu()) {
                return;
            }
            //            if (!isValidPhoneNumber(txt.getText())) {
                //                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ! "
                    //                        + "\n Vui lòng nhập số điện thoại có độ dài 10 hoặc 11 chữ số "
                    //                        + "\n Số điện thoại phải bắt đầu bằng 0.");
                //                return; // Exit the method if the phone number is invalid
                //            }

            vouCher1 nv = getFormData();
            if (nvRepo.add(nv)) {
                loadData();
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                updateMaNhanVienField();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNameVoucher.getText().isEmpty() || txtNgayVoucherBD.getText().isEmpty() || txtNgayVoucherKT.getText().isEmpty() || txtPhamTramGiam.getText() == null) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu");
                return;
            }
            if (!checkDuLieu()) {
                return;
            }
            //            if (!isValidPhoneNumber(txtSDT.getText())) {
                //                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ! "
                    //                        + "\n Vui lòng nhập số điện thoại có độ dài 10 hoặc 11 chữ số "
                    //                        + "\n Số điện thoại phải bắt đầu bằng 0.");
                //                return; // Exit the method if the phone number is invalid
                //            }

            if (tblVoucher.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Chọn nhân viên cần sửa");
                return;
            }
            vouCher1 nv = getFormData();
            nvRepo.Edit(nv);
            loadData();
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
            updateMaNhanVienField();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
    }//GEN-LAST:event_btnSuaActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoConHan;
    private javax.swing.JRadioButton rdoHetHan;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtIDVoucher;
    private javax.swing.JTextField txtNameVoucher;
    private javax.swing.JTextField txtNgayVoucherBD;
    private javax.swing.JTextField txtNgayVoucherKT;
    private javax.swing.JTextField txtPhamTramGiam;
    private javax.swing.JTextField txtTimKiemVocher;
    // End of variables declaration//GEN-END:variables
}
