/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dangnhap;

import Model.ChatLieu;
import Model.Voucher;
import java.util.ArrayList;
import Model.HoaDon;
import Model.HoaDonChiTiet;
import Model.KhachHang1;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Reponse.HoaDonChiTiet_RePones;
import Reponse.HoaDon_Repones;
import Reponse.SanPhamChiTiet_Repones;
import Repository.ChatLieu_repo;
import Repository.HDCT_Repo;
import Repository.HoaDon_Repository;
import Repository.KhachHang_Reposetory;
import Repository.SanPhamChiTiet_Repo;
import Repository.Voucher_Repository;

/**
 *
 * @author ASUS
 */
public class ViiewBanHangFinal extends javax.swing.JPanel {

    DefaultTableModel dtmKH = new DefaultTableModel();
    DefaultTableModel dtmGioHang = new DefaultTableModel();
    DefaultTableModel dtmSanPham = new DefaultTableModel();
    DefaultTableModel dtmHoaDon = new DefaultTableModel();
    Voucher_Repository qlyVoucher = new Voucher_Repository();
    SanPhamChiTiet_Repo qlySPCT = new SanPhamChiTiet_Repo();
    HoaDon_Repository Hd_repo = new HoaDon_Repository();
    HDCT_Repo HDCT_repo = new HDCT_Repo();
    KhachHang_Reposetory KH_repo = new KhachHang_Reposetory();
    ChatLieu_repo CLrepo = new ChatLieu_repo();

    /**
     * Creates new form ViiewBanHangFinal
     */
    public ViiewBanHangFinal() {
        initComponents();
        showCbbVoucher(qlyVoucher.getlist());
        showSanPham(qlySPCT.getSanPham());
        showHoaDon(Hd_repo.getHDchuaThanhToan());
        tbHoaDon.setComponentPopupMenu(jPopupMenu1);
        tbSanPham.setComponentPopupMenu(jPopupMenu2);
        tbGioHang.setComponentPopupMenu(jPopupMenu3);
        tbGioHang.setComponentPopupMenu(jPopupMenu3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        huy = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        ThemSanPham = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        traHang = new javax.swing.JMenuItem();
        ooo = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        txtGiaBe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGiaLon = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        bttSeach = new javax.swing.JButton();
        bttReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        bttTaoHoaDonCho = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        bttTimKiem = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        cbbVoucher = new javax.swing.JComboBox<>();
        txtPhanTramGiam = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtTienDuocGiam = new javax.swing.JTextField();
        txtTienPhaiTra = new javax.swing.JTextField();
        txtTienKhachTra = new javax.swing.JTextField();
        txtTienDu = new javax.swing.JTextField();
        bttTinhTien = new javax.swing.JButton();
        bttThanhToan = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbGioHang = new javax.swing.JTable();

        huy.setText("Huỷ Hoá Đơn");
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(huy);

        ThemSanPham.setText("Thêm Sản Phẩm");
        ThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemSanPhamActionPerformed(evt);
            }
        });
        jPopupMenu2.add(ThemSanPham);

        traHang.setText("Trả Hàng");
        traHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traHangActionPerformed(evt);
            }
        });
        jPopupMenu3.add(traHang);

        ooo.setText("Trả Tất Cả Hàng");
        ooo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oooActionPerformed(evt);
            }
        });
        jPopupMenu3.add(ooo);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Màu Sắc", "Chất Liệu", "Kích Thước", "Thương Hiệu", "Số Lượng Còn Lại", "Đơn Giá"
            }
        ));
        jScrollPane2.setViewportView(tbSanPham);

        jLabel7.setText("Giá Tiền");

        jLabel21.setText("Đến");

        bttSeach.setText("lọc");
        bttSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSeachActionPerformed(evt);
            }
        });

        bttReset.setText("Reset");
        bttReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGiaBe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtGiaLon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(bttReset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtGiaLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(bttSeach)
                    .addComponent(bttReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Hoá Đơn", "Ngày Tạo"
            }
        ));
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDon);

        bttTaoHoaDonCho.setText("Tạo Hóa Đơn Chờ");
        bttTaoHoaDonCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttTaoHoaDonChoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttTaoHoaDonCho, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttTaoHoaDonCho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Mã KH: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 18, -1, -1));

        jLabel23.setText("Tên KH: ");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 44, -1, -1));

        jLabel24.setText("SDT: ");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel3.add(txtMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 18, 187, 20));
        jPanel3.add(txtTenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 44, 187, 20));
        jPanel3.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, 20));

        bttTimKiem.setText("Tìm Kiếm");
        bttTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttTimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(bttTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel25.setText("Tổng Tiền");

        jLabel26.setText("VouCher");

        jLabel29.setText("Mã Khuyến Mãi");

        jLabel31.setText("Tiền Phải Trả");

        jLabel32.setText("Tiền Khách Trả");

        jLabel33.setText("Tiền thừa: ");

        jLabel35.setText("Tiền được giảm");

        cbbVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVoucherActionPerformed(evt);
            }
        });

        jLabel36.setText("%");

        bttTinhTien.setText("Tính Tiền");
        bttTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttTinhTienActionPerformed(evt);
            }
        });

        bttThanhToan.setText("Thanh Toán");
        bttThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTienDu)
                            .addComponent(txtTienKhachTra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTienPhaiTra, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTien)
                            .addComponent(cbbVoucher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTienDuocGiam))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addComponent(txtTienDuocGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel35))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienPhaiTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá"
            }
        ));
        jScrollPane3.setViewportView(tbGioHang);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
public void showCbbVoucher(ArrayList<Voucher> list) {
        cbbVoucher.removeAllItems();
        ArrayList<String> listcbbVC = new ArrayList<>();
        for (Voucher voucher : list) {
            listcbbVC.add(voucher.getTen());
        }
        for (String string : listcbbVC) {
            cbbVoucher.addItem(string);
        }
    }

    public void ShowgioHang(ArrayList<HoaDonChiTiet_RePones> list) {
        dtmGioHang = (DefaultTableModel) tbGioHang.getModel();
        dtmGioHang.setRowCount(0);
        for (HoaDonChiTiet_RePones hoaDonChiTiet_RePones : list) {
            dtmGioHang.addRow(new Object[]{
                hoaDonChiTiet_RePones.getIDSanPhamChiTiet(), hoaDonChiTiet_RePones.getTensp(), hoaDonChiTiet_RePones.getSoLuong(), hoaDonChiTiet_RePones.getDonGia()
            });
        }
    }

    public void showHoaDon(ArrayList<HoaDon_Repones> list) {
        dtmHoaDon = (DefaultTableModel) tbHoaDon.getModel();
        dtmHoaDon.setRowCount(0);
        for (HoaDon_Repones hoaDon_Repones : list) {
            dtmHoaDon.addRow(new Object[]{
                hoaDon_Repones.getIdHoaDon(), hoaDon_Repones.getNgayTao()
            });
        }
    }

    public void showSanPham(ArrayList<SanPhamChiTiet_Repones> list) {
        dtmSanPham = (DefaultTableModel) tbSanPham.getModel();
        dtmSanPham.setRowCount(0);
        for (SanPhamChiTiet_Repones sanPhamChiTiet_Repones : list) {
            dtmSanPham.addRow(new Object[]{
                sanPhamChiTiet_Repones.getIdSanPhamChitiet(), sanPhamChiTiet_Repones.getTen(), sanPhamChiTiet_Repones.getMauSac(), sanPhamChiTiet_Repones.getChatLieu(), sanPhamChiTiet_Repones.getKichThuoc(), sanPhamChiTiet_Repones.getThuongHieu(), sanPhamChiTiet_Repones.getSoLuongConLai(), sanPhamChiTiet_Repones.getGiaTien()
            });
        }
    }

    public int tongTien() {
        int tongTien = 0;
        for (int i = 0; i < tbGioHang.getRowCount(); i++) {
            int soLuongMua = Integer.parseInt(tbGioHang.getValueAt(i, 2).toString());
            int donGia = Integer.parseInt(tbGioHang.getValueAt(i, 3).toString());
            tongTien += (donGia * soLuongMua);
        }
        return tongTien;
    }

    public void tinhToanTien(int tongTien) {
        int tienDuocGiam = tongTien * (Integer.parseInt(txtPhanTramGiam.getText())) / 100;
        txtTienDuocGiam.setText(String.valueOf(tienDuocGiam));
        int tienPhaiTra = tongTien - tienDuocGiam;
        txtTienPhaiTra.setText(String.valueOf(tienPhaiTra));
    }

    public boolean checkChuoi(String chuoi) {
        try {
            Integer.parseInt(chuoi);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public void TraHang(int idHoaDon, int idSanPham, int soLuong) {
        int soLuongHangTon = qlySPCT.getSanPhambyID(idSanPham).get(0).getSoLuongConLai();
        int soLuongUpdate = soLuongHangTon + soLuong;
        qlySPCT.soLuongTon(idSanPham, soLuongUpdate);
    }
    private void bttTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttTimKiemActionPerformed
        // TODO add your handling code here:
        if (txtSDT.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khkhông được để trống Số Điện Thoại");
        } else {
            String sdt = txtSDT.getText();
            KhachHang1 newKH = KH_repo.getKhachHang̣̣(sdt).get(0);
            txtMaKhachHang.setText(String.valueOf(newKH.getIdKhachHang()));
            txtTenKhachHang.setText(newKH.getTenKhachHang());
        }
    }//GEN-LAST:event_bttTimKiemActionPerformed

    private void cbbVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVoucherActionPerformed
        // TODO add your handling code here:
        String tenVoucher = String.valueOf(cbbVoucher.getSelectedItem());
        for (Voucher voucher : qlyVoucher.getVoucherByName(tenVoucher)) {
            txtPhanTramGiam.setText(String.valueOf(voucher.getPhanTramGiam()));
        }
    }//GEN-LAST:event_cbbVoucherActionPerformed

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        // TODO add your handling code here:
        int IDHoaDon = Integer.parseInt(tbHoaDon.getValueAt(tbHoaDon.getSelectedRow(), 0).toString());
        for (int i = 0; i < tbGioHang.getRowCount(); i++) {
            int soLuongGioHang = Integer.parseInt(tbGioHang.getValueAt(i, 2).toString());
            int IDsanPham = Integer.parseInt(tbGioHang.getValueAt(i, 0).toString());
            TraHang(IDHoaDon, IDsanPham, soLuongGioHang);
            HDCT_repo.traHang(IDHoaDon, IDsanPham);
        }
        showSanPham(qlySPCT.getSanPham());
        ShowgioHang(HDCT_repo.getGioHang(IDHoaDon));
        Hd_repo.traHang(IDHoaDon);
        showHoaDon(Hd_repo.getHDchuaThanhToan());
    }//GEN-LAST:event_huyActionPerformed

    private void ThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemSanPhamActionPerformed
        String soLuong = String.valueOf(JOptionPane.showInputDialog("nhập số lượng"));
        if (checkChuoi(soLuong)) {
            int soLuongNhap = Integer.parseInt(soLuong);
            int soLuongTon;
            soLuongTon = Integer.parseInt(tbSanPham.getValueAt(tbSanPham.getSelectedRow(), 6).toString());
            if (soLuongNhap > soLuongTon) {
                JOptionPane.showMessageDialog(this, "nhập quá số lượng");
            } else {
                int idSPCT = Integer.parseInt(tbSanPham.getValueAt(tbSanPham.getSelectedRow(), 0).toString());
                int idHoaDon = 0;
                try {
                    idHoaDon = Integer.parseInt(tbHoaDon.getValueAt(tbHoaDon.getSelectedRow(), 0).toString());
                } finally {
                }
                int giaBan = Integer.parseInt(tbSanPham.getValueAt(tbSanPham.getSelectedRow(), 7).toString());
                int giamGia = 0;
                int soLuongConLai = soLuongTon - soLuongNhap;
                qlySPCT.soLuongTon(idSPCT, soLuongConLai);
                HoaDonChiTiet newHDCT = new HoaDonChiTiet(idHoaDon, idSPCT, soLuongNhap, giaBan, giamGia);
                if (HDCT_repo.getHoaDonChiTiet(idSPCT, idHoaDon).isEmpty()) {
                    HDCT_repo.addHoaDonCT(newHDCT);
                } else {
                    int soLuongGioHang = HDCT_repo.getHoaDonChiTiet(idSPCT, idHoaDon).get(0).getSoLuong();
                    int soLuongCuoi = soLuongNhap + soLuongGioHang;
                    HDCT_repo.soLuongTonGioHang(idHoaDon, idSPCT, soLuongCuoi);
                }
                ShowgioHang(HDCT_repo.getGioHang(idHoaDon));
                showSanPham(qlySPCT.getSanPham());
            }
            txtTongTien.setText(String.valueOf(tongTien()));
            tinhToanTien(tongTien());
        } else {
            JOptionPane.showMessageDialog(this, "số lượng phải là số");
        }
    }//GEN-LAST:event_ThemSanPhamActionPerformed

    private void traHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traHangActionPerformed
        String soLuong = String.valueOf(JOptionPane.showInputDialog("nhập số lượng"));
        if (checkChuoi(soLuong)) {
            int soLuongNhap = Integer.parseInt(soLuong);
            int soLuongOGioHang;
            soLuongOGioHang = Integer.parseInt(tbGioHang.getValueAt(tbGioHang.getSelectedRow(), 2).toString());
            if (soLuongNhap > soLuongOGioHang) {
                JOptionPane.showMessageDialog(this, "nhập quá số lượng");
            } else {
                int idHoaDon = Integer.parseInt(tbHoaDon.getValueAt(tbHoaDon.getSelectedRow(), 0).toString());
                int idSPCT = Integer.parseInt(tbGioHang.getValueAt(tbGioHang.getSelectedRow(), 0).toString());
                for (int i = 0; i < tbSanPham.getRowCount(); i++) {
                    int idSanPham = Integer.parseInt(tbSanPham.getValueAt(i, 0).toString());
                    if (idSPCT == idSanPham) {
                        int soLuongton = Integer.parseInt(tbSanPham.getValueAt(i, 6).toString());
                        int soluongsanpham = soLuongton + soLuongNhap;
                        int soLuongoGioHangSaukhitra = soLuongOGioHang - soLuongNhap;
                        qlySPCT.soLuongTon(idSPCT, soluongsanpham);
                        HDCT_repo.soLuongTonGioHang(idHoaDon, idSPCT, soLuongoGioHangSaukhitra);
                        ShowgioHang(HDCT_repo.getGioHang(idHoaDon));
                        showSanPham(qlySPCT.getSanPham());
                        int tongTien = tongTien();
                        txtTongTien.setText(String.valueOf(tongTien));
                        tinhToanTien(tongTien());
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "số lượng phải là số");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_traHangActionPerformed

    private void oooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oooActionPerformed
        int idHoaDon = Integer.parseInt(tbHoaDon.getValueAt(tbHoaDon.getSelectedRow(), 0).toString());
        int IDsanPham = Integer.parseInt(tbGioHang.getValueAt(tbGioHang.getSelectedRow(), 0).toString());
        int soLuong = Integer.parseInt(tbGioHang.getValueAt(tbGioHang.getSelectedRow(), 2).toString());
        TraHang(idHoaDon, IDsanPham, soLuong);
        HDCT_repo.traHang(idHoaDon, IDsanPham);
        ShowgioHang(HDCT_repo.getGioHang(idHoaDon));        // TODO add your handling code here:
    }//GEN-LAST:event_oooActionPerformed

    private void bttTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttTinhTienActionPerformed
        int thanhTien = Integer.valueOf(txtTienPhaiTra.getText());
        if (txtTienKhachTra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "khong the de trong");
        } else {
            if (checkChuoi(txtTienKhachTra.getText())) {
                int tienKhachTra = Integer.valueOf(txtTienKhachTra.getText());
                if (tienKhachTra <= thanhTien) {
                    JOptionPane.showMessageDialog(this, "khach chưa tra du tien , khong the thanh toan");
                } else {
                    int tienThua = tienKhachTra - tongTien();
                    txtTienDu.setText(String.valueOf(tienThua));
                }
            } else {
                JOptionPane.showMessageDialog(this, "phai la so");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bttTinhTienActionPerformed

    private void bttThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThanhToanActionPerformed
        String tienDU = txtTienDu.getText();

        if (tienDU.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "VUi lòng tính tiền trước");
        } else {
            int idHoaDon = Integer.parseInt(tbHoaDon.getValueAt(tbHoaDon.getSelectedRow(), 0).toString());
            int tongTien = Integer.valueOf(txtTongTien.getText());
            int tienDuocGiam = Integer.valueOf(txtTienDuocGiam.getText());
            int thanhTien = Integer.valueOf(txtTienPhaiTra.getText());
            Hd_repo.thanhtoan(thanhTien, tongTien, tienDuocGiam, idHoaDon);
            showHoaDon(Hd_repo.getHDchuaThanhToan());
            txtTienKhachTra.setText("");
            txtTienDu.setText("");
        }
    }//GEN-LAST:event_bttThanhToanActionPerformed

    private void bttTaoHoaDonChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttTaoHoaDonChoActionPerformed
        // TODO add your handling code here:
        Hd_repo.addHoaDon();
        showHoaDon(Hd_repo.getHDchuaThanhToan());
    }//GEN-LAST:event_bttTaoHoaDonChoActionPerformed

    private void tbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMouseClicked
        // TODO add your handling code here:
        int idHoaDon = Integer.parseInt(tbHoaDon.getValueAt(tbHoaDon.getSelectedRow(), 0).toString());
        ShowgioHang(HDCT_repo.getGioHang(idHoaDon));
        int tongTien = tongTien();
        txtTongTien.setText(String.valueOf(tongTien));
        tinhToanTien(tongTien);
    }//GEN-LAST:event_tbHoaDonMouseClicked

    private void bttSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSeachActionPerformed
        // TODO add your handling code here:
        if (txtGiaBe.getText().trim().isEmpty() || txtGiaBe.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Được để trống giá cần tìm");
        } else {
            int giaBe = Integer.valueOf(txtGiaBe.getText());
            int giaLon = Integer.valueOf(txtGiaLon.getText());
            showSanPham(qlySPCT.getSanPhamtbyKhoangGia(giaLon, giaBe));
        }
    }//GEN-LAST:event_bttSeachActionPerformed

    private void bttResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttResetActionPerformed
        // TODO add your handling code here:
        showSanPham(qlySPCT.getSanPham());
    }//GEN-LAST:event_bttResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ThemSanPham;
    private javax.swing.JButton bttReset;
    private javax.swing.JButton bttSeach;
    private javax.swing.JButton bttTaoHoaDonCho;
    private javax.swing.JButton bttThanhToan;
    private javax.swing.JButton bttTimKiem;
    private javax.swing.JButton bttTinhTien;
    private javax.swing.JComboBox<String> cbbVoucher;
    private javax.swing.JMenuItem huy;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem ooo;
    private javax.swing.JTable tbGioHang;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JMenuItem traHang;
    private javax.swing.JTextField txtGiaBe;
    private javax.swing.JTextField txtGiaLon;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtPhanTramGiam;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTienDu;
    private javax.swing.JTextField txtTienDuocGiam;
    private javax.swing.JTextField txtTienKhachTra;
    private javax.swing.JTextField txtTienPhaiTra;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
